# Generated by Django 5.2.4 on 2025-07-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_describtion_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventory',
            new_name='invertory',
        ),
    ]
